<!-- They are used for debugging, logs

Debugging : is the process of finding root causes, workarounds, and fixing the bugs.
Logs : Collection of recorded messages generated by php application, which containing information about the events, errors, warning, and other significant information which can be used for debugging and monitoring purposes.

-->
<?php

echo "MAGIC CONSTANTS"."<br>";

// echo "Give current line number : " . __LINE__;
// echo "Give complete file path of this file : " . __FILE__;
// echo "Give Directory of this file : " . __DIR__;

function myFunction() {
    echo "Give Function Name : " . __FUNCTION__;
}

myFunction(); 